# Generated by Django 4.1.7 on 2023-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviewer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/img/Без названия.png",
                null=True,
                upload_to="",
                verbose_name="Image",
            ),
        ),
    ]
